logging:
  level:
    fr.nicopico: debug
    org.springframework.web: debug
    org.hibernate: warn
    web: debug
    liquibase: debug

spring:
  jpa:
    generate-ddl: false
  h2:
    console:
      enabled: false
  liquibase:
    contexts: dev

my.typesafe.properties.text: ${MY_TEXT} # Use MY_TEXT environment variable
