logging:
  level:
    fr.nicopico: debug
    org.springframework.web: debug
    org.hibernate: warn

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/blog
    username: root
    password: password
  jpa:
    generate-ddl: true
