logging:
  level:
    fr.nicopico: debug
    org.springframework.web: debug
    org.hibernate: warn
    web: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/blog
    username: root
    password: password
  jpa:
    generate-ddl: false
  h2:
    console:
      enabled: true
  liquibase:
    contexts: dev

my.typesafe.properties.text: ${MY_TEXT} # Use MY_TEXT environment variable
