version: '3.4'

services:
  blog-db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog
    volumes:
      - blog-db-storage:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  blog-db-storage:
